argoCDApps:
  applications:
    argocd-apps:
      namespace: argocd
      project: default
      source:
        repoURL: https://github.com/talesrc/infrastructure.git
        path: helm/charts/argocd-apps
        targetRevision: develop
        helm:
          valueFiles:
            - ../../values/argocd-apps/applications.yaml
          ignoreMissingValueFiles: false
      destination:
        name: in-cluster
        namespace: argocd
      syncPolicy:
        automated:
          prune: false
          selfHeal: false
        syncOptions:
        - CreateNamespace=true
