repositoriesToMirror:
  infrastructure-interview:
    mirroredRepositoryURL: https://github.com/talesrc/infrastructure-interview-challenge.git
    hostedOn: github
    isPrivate: false

gitea:
  image:
    rootless: true
  redis-cluster:
    enabled: true
  postgresql:
    enabled: true
  postgresql-ha:
    enabled: false

  persistence:
    enabled: false

  ingress:
    enabled: true
    hosts:
    - host: git.taleco.local
      paths:
        - path: /
          pathType: Prefix

  service:
    ssh:
      type: LoadBalancer

  admin:
    username: giteaAdmin
    password: giteaAdmin
    email: admin@gitea.com
  
  redis-cluster:
    enabled: false
  
  redis:
    enabled: true
