{{- if .Values.repositoriesToMirror }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gitea.jobs.mirrorRepository.configmap.name" . }}
data:
  {{ include "gitea.jobs.mirrorRepository.script.name" . }}: |
    set -eux pipefail

    echo "Requesting migration..."
    curl -X POST -H "Content-Type: application/json" \
    -u $GITEA_USERNAME:$GITEA_PASSWORD -so - \
    -d '{
        "repo_name": "'$MIRRORED_REPOSITORY_NAME'",
        "clone_addr": "'$MIRRORED_REPOSITORY_URL'",
        "issues": true,
        "labels": true,
        "mirror": true,
        "mirror_interval": "10m",
        "private": '$IS_PRIVATE',
        "pull_requests": true,
        "releases": true,
        "service": "'$HOSTED_ON'",
        "wiki": true
    }' $GITEA_URL/api/v1/repos/migrate
{{- end }}  
